name: go_native_toolchain
description: A library to invoke the native Go compiler installed on the host machine.
version: 0.1.0
repository: https://github.com/csnewman/flutter-go-bridge

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cli_config: ^0.1.2
  logging: ^1.2.0
  native_assets_cli: ^0.4.2
  native_toolchain_c: ^0.3.4+1
  ffi: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
