// This code was generated by flutter-go-bridge. Do not manually edit.
package main

import (
	"errors"
	"fmt"
	"sync"
	"sync/atomic"
	"unsafe"

	orig "github.com/csnewman/flutter-go-bridge/example"
	"github.com/csnewman/flutter-go-bridge/runtime"
)

/*
#include <stdlib.h>
#include <stdint.h>

typedef struct {
	int x;
	int y;
	void* name;
} fgb_vt_point;

typedef struct {
	int res;
	void* err;
} fgb_ret_add;

typedef struct {
	fgb_vt_point res;
	void* err;
} fgb_ret_add_points;

typedef struct {
	int res;
	void* err;
} fgb_ret_add_error;
*/
import "C"

var (
	handles   = sync.Map{}
	handleIdx uint64
	ErrDart   = errors.New("dart")
)

// Required by cgo
func main() {}

//export fgbinternal_init
func fgbinternal_init(p unsafe.Pointer) unsafe.Pointer {
	err := runtime.InitializeApi(p)

	var cerr unsafe.Pointer
	if err != nil {
		cerr = unsafe.Pointer(C.CString(err.Error()))
	}

	return cerr
}

//export fgbinternal_alloc
func fgbinternal_alloc(size C.intptr_t) unsafe.Pointer {
	return C.malloc((C.uintptr_t)(size))
}

//export fgbinternal_free
func fgbinternal_free(ptr unsafe.Pointer) {
	C.free(ptr)
}

func mapToString(from unsafe.Pointer) string {
	res := C.GoString((*C.char)(from))
	C.free(from)
	return res
}

func mapFromString(from string) unsafe.Pointer {
	return unsafe.Pointer(C.CString(from))
}

func mapToError(from unsafe.Pointer) error {
	res := C.GoString((*C.char)(from))
	C.free(from)
	return fmt.Errorf("%w: %v", ErrDart, res)
}

func mapFromError(from error) unsafe.Pointer {
	return unsafe.Pointer(C.CString(from.Error()))
}

//export fgbempty_point
func fgbempty_point() (res C.fgb_vt_point) {
	return
}

func mapToPoint(from C.fgb_vt_point) (res orig.Point) {
	res.X = (int)(from.x)
	res.Y = (int)(from.y)
	res.Name = mapToString(from.name)
	return
}

func mapFromPoint(from orig.Point) (res C.fgb_vt_point) {
	res.x = (C.int)(from.X)
	res.y = (C.int)(from.Y)
	res.name = mapFromString(from.Name)
	return
}

//export fgb_add
func fgb_add(a C.int, b C.int) (resw C.fgb_ret_add) {
	defer func() {
		r := recover()
		if r == nil {
			return
		}

		resw = C.fgb_ret_add{
			err: unsafe.Pointer(C.CString(fmt.Sprintf("panic: %v", r))),
		}
	}()
	
	aGo := (int)(a)
	bGo := (int)(b)
	gres := orig.Add(aGo, bGo)
	
	cres := (C.int)(gres)

	return C.fgb_ret_add{
		res: cres,
	}
}

//export fgbasync_add
func fgbasync_add(a C.int, b C.int, fgbPort int64) {
	go func() {
		h := atomic.AddUint64(&handleIdx, 1)
		if h == 0 {
			panic("ran out of handle space")
		}

		handles.Store(h, fgb_add(a, b))

		sent := runtime.Send(fgbPort, []uint64{h}, func() {
			handles.LoadAndDelete(h)
		})
		if !sent {
			handles.LoadAndDelete(h)
		}
	}()
}

//export fgbasyncres_add
func fgbasyncres_add(h uint64) C.fgb_ret_add {
	v, ok := handles.LoadAndDelete(h)
	if !ok {
		return C.fgb_ret_add{
			err: unsafe.Pointer(C.CString("result handle is not valid")),
		}
	}

	return (v).(C.fgb_ret_add)
}

//export fgb_add_points
func fgb_add_points(a C.fgb_vt_point, b C.fgb_vt_point) (resw C.fgb_ret_add_points) {
	defer func() {
		r := recover()
		if r == nil {
			return
		}

		resw = C.fgb_ret_add_points{
			err: unsafe.Pointer(C.CString(fmt.Sprintf("panic: %v", r))),
		}
	}()
	
	aGo := mapToPoint(a)
	bGo := mapToPoint(b)
	gres := orig.AddPoints(aGo, bGo)
	
	cres := mapFromPoint(gres)

	return C.fgb_ret_add_points{
		res: cres,
	}
}

//export fgbasync_add_points
func fgbasync_add_points(a C.fgb_vt_point, b C.fgb_vt_point, fgbPort int64) {
	go func() {
		h := atomic.AddUint64(&handleIdx, 1)
		if h == 0 {
			panic("ran out of handle space")
		}

		handles.Store(h, fgb_add_points(a, b))

		sent := runtime.Send(fgbPort, []uint64{h}, func() {
			handles.LoadAndDelete(h)
		})
		if !sent {
			handles.LoadAndDelete(h)
		}
	}()
}

//export fgbasyncres_add_points
func fgbasyncres_add_points(h uint64) C.fgb_ret_add_points {
	v, ok := handles.LoadAndDelete(h)
	if !ok {
		return C.fgb_ret_add_points{
			err: unsafe.Pointer(C.CString("result handle is not valid")),
		}
	}

	return (v).(C.fgb_ret_add_points)
}

//export fgb_add_error
func fgb_add_error(a C.int, b C.int) (resw C.fgb_ret_add_error) {
	defer func() {
		r := recover()
		if r == nil {
			return
		}

		resw = C.fgb_ret_add_error{
			err: unsafe.Pointer(C.CString(fmt.Sprintf("panic: %v", r))),
		}
	}()
	
	aGo := (int)(a)
	bGo := (int)(b)
	gres, gerr := orig.AddError(aGo, bGo)
	if gerr != nil {
		return C.fgb_ret_add_error{
			err: unsafe.Pointer(C.CString(gerr.Error())),
		}
	}
	
	cres := (C.int)(gres)

	return C.fgb_ret_add_error{
		res: cres,
	}
}

//export fgbasync_add_error
func fgbasync_add_error(a C.int, b C.int, fgbPort int64) {
	go func() {
		h := atomic.AddUint64(&handleIdx, 1)
		if h == 0 {
			panic("ran out of handle space")
		}

		handles.Store(h, fgb_add_error(a, b))

		sent := runtime.Send(fgbPort, []uint64{h}, func() {
			handles.LoadAndDelete(h)
		})
		if !sent {
			handles.LoadAndDelete(h)
		}
	}()
}

//export fgbasyncres_add_error
func fgbasyncres_add_error(h uint64) C.fgb_ret_add_error {
	v, ok := handles.LoadAndDelete(h)
	if !ok {
		return C.fgb_ret_add_error{
			err: unsafe.Pointer(C.CString("result handle is not valid")),
		}
	}

	return (v).(C.fgb_ret_add_error)
}
