name: Integration Tests
on: [ push, workflow_dispatch ]
jobs:
  android:
    runs-on: macos-latest
    steps:
      - name: Set up Java 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-native-assets
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          target: default
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            flutter doctor
            cd exampleapp && flutter test -d android --timeout none -v integration_test/
  ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-native-assets
      - uses: futureware-tech/simulator-action@v3
        id: sim
        with:
          model: 'iPhone 14'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: cd exampleapp && flutter test -d ${{ steps.sim.outputs.udid }} --timeout none -v integration_test/
  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-native-assets
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: cd exampleapp && flutter test -d macos --timeout none -v integration_test/
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-native-assets
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential ninja-build libgtk-3-dev
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1
      - run: flutter config --enable-linux-desktop
      - run: cd exampleapp && flutter test -d linux --timeout none -v integration_test/
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter config --enable-native-assets
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: flutter config --enable-windows-desktop
      - run: cd exampleapp && flutter test -d windows --timeout none -v integration_test/
