name: Integration Tests
on: [ push, workflow_dispatch ]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential ninja-build libgtk-3-dev
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v1
      - run: flutter config --enable-linux-desktop
      - run: cd exampleapp && flutter test -d linux --timeout none -v integration_test/
